### ISSUE TITLE
FACEBOOK連携

### ISSUE THREAD

**Issue by sige1115** [xxmogi/syukuba#4]
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-page"
data-href="https://www.facebook.com/hodogayasyukubafest/timeline"
data-tabs="timeline" data-small-header="false"
data-adapt-container-width="true" data-hide-cover="false"
data-show-facepile="false"><blockquote
cite="https://www.facebook.com/hodogayasyukubafest/timeline"
class="fb-xfbml-parse-ignore"><a
href="https://www.facebook.com/hodogayasyukubafest/timeline">保土ケ谷宿場まつり</a></blockquote></div>

<iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fhodogayasyukubafest%2Ftimeline&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=false&appId"
width="340" height="500" style="border:none;overflow:hidden"
scrolling="no" frameborder="0" allowTransparency="true"></iframe>

**Comment by xxmogi** [comment]
Facebook 用の[Page plugin](https://developers.facebook.com/docs/plugins/page-plugin?locale=ja_JP) 追加。

あと、Share時に画像や説明が表示されるように[Open Graph](https://developers.facebook.com/docs/sharing/opengraph/object-properties) プロパティも追加。
