### ISSUE TITLE
クラウドファンディングの告知を載せてほしい。

### ISSUE THREAD

**Issue by dproject21** [xxmogi/syukuba#8]
自分でプルリクエスト出すかもしれませんが...

いま動かしているクラウドファンディングの告知を、公式サイトのほうに展開したいです。

最小プランとして、リンクのみ。
できれば、別途ページを起こして

* YouTubeの映像の埋め込み
* クラウドファンディング企画の簡単な説明

も載せられると嬉しいです。

**Comment by xxmogi** [comment]
クラウドファンディングのページ追加してみました。

http://syukuba.net/2016/crowdfunding.html

コンテンツ内容は結構適当なので、何かあれば対応します。

**Comment by dproject21** [comment]
確認しました。ありがとうございます！

小町企画のページ分量も踏まえて、これでOKです。
ページ強化したい。という話が出てきたら、別途Issue立てます。
